operator:
  image: worker-operator-ent
  tag: 1.6.1
  pullPolicy: IfNotPresent
  logLevel: INFO

## Base64 encoded secret values from controller cluster
controllerSecret:
  namespace:
  endpoint:
  ca.crt:
  token:

cluster:
  name:
  nodeIp: # This field is deprecated. You can set nodeIPs through cluster spec.
  endpoint:

router:
  image: cmd-nse-vl3
  tag: 1.0.3
  pullPolicy: IfNotPresent                                                                                     

routerSidecar:
  image: kubeslice-router-sidecar
  tag: 1.4.3
  pullPolicy: IfNotPresent

netop:
  networkInterface: eth0
  image: netops
  tag: 0.2.0
  pullPolicy: IfNotPresent

gateway:
  image: gw-sidecar
  tag: 0.3.1
  pullPolicy: IfNotPresent
  logLevel: INFO

gatewayEdge:
  image: slicegw-edge
  tag: 1.0.4

openvpn:
  server:
    image: openvpn-server.alpine.amd64
    tag: 1.0.1
    pullPolicy: IfNotPresent
  client:
    image: openvpn-client.alpine.amd64
    tag: 1.0.0
    pullPolicy: IfNotPresent

dns:
  image: dns
  tag: 0.1.0
  pullPolicy: IfNotPresent

envoy:
  gateway:
    image: envoygateway
    tag: 1.0.0
  proxy:
    image: envoyproxy-distroless
    tag: 1.0.0

jaeger:
  enabled: false
  
events:
  disabled: false

metrics:
  insecure: false
  metricResolution: "15s"
  imagePullPolicy: IfNotPresent

# username & password & email values for imagePullSecrets has to provided to create a secret
imagePullSecrets:
  repository: https://index.docker.io/v1/
  username:
  password:
  email:

controllerNamespace: kubeslice-controller

# if you're installing in openshift cluster make this variable true
global:
  imageRegistry: eengccoelabacrcac1.azurecr.io/sft0/kubeslice
  profile:
    openshift: false
